model_list:
  - model_name: claude-3-5-sonnet-20241022
    litellm_params:
      model: nvidia_nim/meta/llama-3.1-8b-instruct
      api_key: "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"
      drop_params: true
      additional_drop_params: ["output_config"]
  - model_name: claude-sonnet-4-6
    litellm_params:
      model: nvidia_nim/meta/llama-3.1-8b-instruct
      api_key: "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"
      drop_params: true
      additional_drop_params: ["output_config"]
  - model_name: claude-3-5-sonnet
    litellm_params:
      model: nvidia_nim/meta/llama-3.1-8b-instruct
      api_key: "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"
      drop_params: true
      additional_drop_params: ["output_config"]
  - model_name: claude-opus-4-7
    litellm_params:
      model: nvidia_nim/meta/llama-3.1-8b-instruct
      api_key: "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"
      drop_params: true
      additional_drop_params: ["output_config"]
